# This is the configuration file for the plugin

# The sign that will be used to join users to a job
# The first line can be anything, the second line must be the job name
signs:
  - You will be
  - <JOB_NAME>
  - ""
  - ""

cooldown:
  # The cooldown duration in seconds to change jobs
  time: 60
  error: "You must wait <TIME> seconds before changing a job"
